{extends file='layout.tpl'}
{block name='body'}
    <div id="page">
        <div id="header">
            <h1 id="logo"><a href="/">pwdb</a></h1>
            <form id="header-search" action="/search" method="get">
                <span id="level-select-display" style="display: none;">
                Level adjustment: <select id="level-select">
                    <option value='0'>None</option>
                    <option value='1'>Level 1</option>
                    <option value='2'>Level 2</option>
                    <option value='3'>Level 3</option>
                    <option value='4'>Level 4</option>
                    <option value='5'>Level 5</option>
                    <option value='6'>Level 6</option>
                    <option value='7'>Level 7</option>
                    <option value='8'>Level 8</option>
                    <option value='9'>Level 9</option>
                    <option value='10'>Level 10</option>
                    <option value='11'>Level 11</option>
                    <option value='12'>Level 12</option>
                    <option value='13'>Level 13</option>
                    <option value='14'>Level 14</option>
                    <option value='15'>Level 15</option>
                    <option value='16'>Level 16</option>
                    <option value='17'>Level 17</option>
                    <option value='18'>Level 18</option>
                    <option value='19'>Level 19</option>
                    <option value='20'>Level 20</option>
                    <option value='21'>Level 21</option>
                    <option value='22'>Level 22</option>
                    <option value='23'>Level 23</option>
                    <option value='24'>Level 24</option>
                    <option value='25'>Level 25</option>
                    <option value='26'>Level 26</option>
                    <option value='27'>Level 27</option>
                    <option value='28'>Level 28</option>
                    <option value='29'>Level 29</option>
                    <option value='30'>Level 30</option>
                    <option value='31'>Level 31</option>
                    <option value='32'>Level 32</option>
                    <option value='33'>Level 33</option>
                    <option value='34'>Level 34</option>
                    <option value='35'>Level 35</option>
                    <option value='36'>Level 36</option>
                    <option value='37'>Level 37</option>
                    <option value='38'>Level 38</option>
                    <option value='39'>Level 39</option>
                    <option value='40'>Level 40</option>
                    <option value='41'>Level 41</option>
                    <option value='42'>Level 42</option>
                    <option value='43'>Level 43</option>
                    <option value='44'>Level 44</option>
                    <option value='45'>Level 45</option>
                    <option value='46'>Level 46</option>
                    <option value='47'>Level 47</option>
                    <option value='48'>Level 48</option>
                    <option value='49'>Level 49</option>
                    <option value='50'>Level 50</option>
                    <option value='51'>Level 51</option>
                    <option value='52'>Level 52</option>
                    <option value='53'>Level 53</option>
                    <option value='54'>Level 54</option>
                    <option value='55'>Level 55</option>
                    <option value='56'>Level 56</option>
                    <option value='57'>Level 57</option>
                    <option value='58'>Level 58</option>
                    <option value='59'>Level 59</option>
                    <option value='60'>Level 60</option>
                    <option value='61'>Level 61</option>
                    <option value='62'>Level 62</option>
                    <option value='63'>Level 63</option>
                    <option value='64'>Level 64</option>
                    <option value='65'>Level 65</option>
                    <option value='66'>Level 66</option>
                    <option value='67'>Level 67</option>
                    <option value='68'>Level 68</option>
                    <option value='69'>Level 69</option>
                    <option value='70'>Level 70</option>
                    <option value='71'>Level 71</option>
                    <option value='72'>Level 72</option>
                    <option value='73'>Level 73</option>
                    <option value='74'>Level 74</option>
                    <option value='75'>Level 75</option>
                    <option value='76'>Level 76</option>
                    <option value='77'>Level 77</option>
                    <option value='78'>Level 78</option>
                    <option value='79'>Level 79</option>
                    <option value='80'>Level 80</option>
                    <option value='81'>Level 81</option>
                    <option value='82'>Level 82</option>
                    <option value='83'>Level 83</option>
                    <option value='84'>Level 84</option>
                    <option value='85'>Level 85</option>
                    <option value='86'>Level 86</option>
                    <option value='87'>Level 87</option>
                    <option value='88'>Level 88</option>
                    <option value='89'>Level 89</option>
                    <option value='90'>Level 90</option>
                    <option value='91'>Level 91</option>
                    <option value='92'>Level 92</option>
                    <option value='93'>Level 93</option>
                    <option value='94'>Level 94</option>
                    <option value='95'>Level 95</option>
                    <option value='96'>Level 96</option>
                    <option value='97'>Level 97</option>
                    <option value='98'>Level 98</option>
                    <option value='99'>Level 99</option>
                    <option value='100'>Level 100</option>
                    <option value='101'>Level 101</option>
                    <option value='102'>Level 102</option>
                    <option value='103'>Level 103</option>
                    <option value='104'>Level 104</option>
                    <option value='105'>Level 105</option>
                </select>
                </span>
                <input type="search" id="search_box" placeholder="Type to search…" name="q" value="{block name=default_search}{/block}">
            </form>
        </div>
        <div id="main-content">
            {block name='content'}{/block}
        </div>
    </div>
{/block}
